ALTER TABLE UDP ADD "FOLDER_ID" bigint NULL;
ALTER TABLE UDP ADD FOREIGN KEY (FOLDER_ID) REFERENCES FOLDER(ID) ON DELETE CASCADE;
ALTER TABLE UDP ADD CONSTRAINT UDP_EXCLUSIVE_CONTAINER_TYPE_CONSTRAINT CHECK((TESTCASE_ID IS NULL AND FOLDER_ID IS NOT NULL) OR (TESTCASE_ID IS NOT NULL AND FOLDER_ID IS NULL));
ALTER TABLE UDP ADD CONSTRAINT UDP_UNIQUE_SEQUENCE_CONSTRAINT2 UNIQUE(FOLDER_ID, SEQUENCE);
ALTER TABLE UDP ADD CONSTRAINT UDP_UNIQUE_NAME_CONSTRAINT2 UNIQUE(FOLDER_ID, NAME);

ALTER TABLE DATATABLE_COLUMN ALTER COLUMN TESTCASE_ID bigint NULL;
ALTER TABLE DATATABLE_COLUMN ADD "TESTSTEP_ID" bigint NULL;
ALTER TABLE DATATABLE_COLUMN ADD FOREIGN KEY (TESTSTEP_ID) REFERENCES TESTSTEP(ID) ON DELETE CASCADE;
ALTER TABLE DATATABLE_COLUMN ADD CONSTRAINT DATATABLE_COLUMN_EXCLUSIVE_CONTAINER_TYPE_CONSTRAINT CHECK((TESTCASE_ID IS NULL AND TESTSTEP_ID IS NOT NULL) OR (TESTCASE_ID IS NOT NULL AND TESTSTEP_ID IS NULL));
ALTER TABLE DATATABLE_COLUMN ADD CONSTRAINT DATATABLE_COLUMN_UNIQUE_SEQUENCE_CONSTRAINT2 UNIQUE(TESTSTEP_ID, SEQUENCE);
ALTER TABLE DATATABLE_COLUMN ADD CONSTRAINT DATATABLE_COLUMN_UNIQUE_NAME_CONSTRAINT2 UNIQUE(TESTSTEP_ID, NAME);

insert into datatable_column (name, type, sequence, teststep_id) select 'Caption', 'String', 1, id, from teststep;

delete from testcase_run;

ALTER TABLE TESTSTEP_RUN RENAME TO TESTSTEP_ATOMICRUN_CONTENT;
ALTER TABLE TESTSTEP_ATOMICRUN_CONTENT DROP COLUMN "ID";
ALTER TABLE TESTSTEP_ATOMICRUN_CONTENT ADD "ID" IDENTITY PRIMARY KEY;
DROP SEQUENCE TESTSTEP_RUN_SEQUENCE;
ALTER TABLE TESTSTEP_ATOMICRUN_CONTENT ADD "TESTSTEP_RUN_ID" BIGINT NOT NULL;
ALTER TABLE TESTSTEP_ATOMICRUN_CONTENT ADD "TESTSTEP_INDIVIDUALRUN_ID" BIGINT;

CREATE TABLE IF NOT EXISTS teststep_run (
    id IDENTITY PRIMARY KEY, testcase_run_id BIGINT NOT NULL, testcase_individualrun_id BIGINT,
    starttime TIMESTAMP NOT NULL, duration BIGINT NOT NULL, result varchar(15) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (testcase_run_id) REFERENCES testcase_run(id) ON DELETE CASCADE,
    FOREIGN KEY (testcase_individualrun_id) REFERENCES testcase_individualrun(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS teststep_individualrun (id IDENTITY PRIMARY KEY,
    teststep_run_id BIGINT NOT NULL, caption VARCHAR(500),
    starttime TIMESTAMP NOT NULL, duration BIGINT NOT NULL, result varchar(15) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (teststep_run_id) REFERENCES teststep_run(id) ON DELETE CASCADE
);

ALTER TABLE TESTSTEP_ATOMICRUN_CONTENT ADD FOREIGN KEY (TESTSTEP_RUN_ID) REFERENCES TESTSTEP_RUN(ID) ON DELETE CASCADE;
ALTER TABLE TESTSTEP_ATOMICRUN_CONTENT ADD FOREIGN KEY (TESTSTEP_INDIVIDUALRUN_ID) REFERENCES TESTSTEP_INDIVIDUALRUN(ID) ON DELETE CASCADE;
ALTER TABLE TESTSTEP_ATOMICRUN_CONTENT DROP COLUMN "TESTCASE_RUN_ID";
ALTER TABLE TESTSTEP_ATOMICRUN_CONTENT DROP COLUMN "TESTCASE_INDIVIDUALRUN_ID";
ALTER TABLE TESTSTEP_ATOMICRUN_CONTENT DROP COLUMN "STARTTIME";
ALTER TABLE TESTSTEP_ATOMICRUN_CONTENT DROP COLUMN "DURATION";
ALTER TABLE TESTSTEP_ATOMICRUN_CONTENT DROP COLUMN "RESULT";