ALTER TABLE TESTSTEP_INDIVIDUALRUN ADD TESTSTEP_REPEATRUN_ID BIGINT;
ALTER TABLE TESTSTEP_INDIVIDUALRUN ADD FOREIGN KEY (TESTSTEP_REPEATRUN_ID) REFERENCES TESTSTEP_REPEATRUN(ID) ON DELETE CASCADE;
ALTER TABLE TESTSTEP_ATOMICRUN_RESULT ADD TESTSTEP_REPEATRUN_ID BIGINT;
ALTER TABLE TESTSTEP_ATOMICRUN_RESULT ADD FOREIGN KEY (TESTSTEP_REPEATRUN_ID) REFERENCES TESTSTEP_REPEATRUN(ID) ON DELETE CASCADE;