CREATE TABLE IF NOT EXISTS teststep_repeatrun (id IDENTITY PRIMARY KEY, index INTEGER NOT NULL, starttime TIMESTAMP NOT NULL, duration BIGINT NOT NULL, result varchar(15) NOT NULL, teststep_run_id BIGINT NOT NULL, created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (teststep_run_id) REFERENCES teststep_run(id) ON DELETE CASCADE);
ALTER TABLE TESTSTEP_INDIVIDUALRUN ADD TESTSTEP_REPEATRUN_ID BIGINT;
ALTER TABLE TESTSTEP_INDIVIDUALRUN ADD FOREIGN KEY (TESTSTEP_REPEATRUN_ID) REFERENCES TESTSTEP_REPEATRUN(ID) ON DELETE CASCADE;
ALTER TABLE TESTSTEP_ATOMICRUN_RESULT ADD TESTSTEP_REPEATRUN_ID BIGINT;
ALTER TABLE TESTSTEP_ATOMICRUN_RESULT ADD FOREIGN KEY (TESTSTEP_REPEATRUN_ID) REFERENCES TESTSTEP_REPEATRUN(ID) ON DELETE CASCADE;

ALTER TABLE TESTSTEP ADD RUN_PATTERN CLOB;

ALTER TABLE DATATABLE_COLUMN DROP CONSTRAINT DATATABLE_COLUMN_PROPERTY_NAME_CONSTRAINT;
ALTER TABLE DATATABLE_COLUMN ADD CONSTRAINT DATATABLE_COLUMN_PROPERTY_NAME_CONSTRAINT CHECK((NOT ("NAME" IN('Test_Case_Start_Time', 'Test_Step_Start_Time', 'Test_Step_Repeat_Run_Index', 'Test_Case_Individual_Start_Time'))) AND REGEXP_LIKE("NAME", '^[a-zA-Z_$][a-zA-Z_$0-9]*$'));
ALTER TABLE UDP DROP CONSTRAINT UDP_PROPERTY_NAME_CONSTRAINT;
ALTER TABLE UDP ADD CONSTRAINT UDP_PROPERTY_NAME_CONSTRAINT CHECK((NOT ("NAME" IN('Test_Case_Start_Time', 'Test_Step_Start_Time', 'Test_Step_Repeat_Run_Index', 'Test_Case_Individual_Start_Time'))) AND REGEXP_LIKE("NAME", '^[a-zA-Z_$][a-zA-Z_$0-9]*$'));
ALTER TABLE PROPERTY_EXTRACTOR DROP CONSTRAINT PROPERTY_EXTRACTOR_PROPERTY_NAME_CONSTRAINT;
ALTER TABLE PROPERTY_EXTRACTOR ADD CONSTRAINT PROPERTY_EXTRACTOR_PROPERTY_NAME_CONSTRAINT CHECK((NOT ("PROPERTY_NAME" IN('Test_Case_Start_Time', 'Test_Step_Start_Time', 'Test_Step_Repeat_Run_Index', 'Test_Case_Individual_Start_Time'))) AND REGEXP_LIKE("PROPERTY_NAME", '^[a-zA-Z_$][a-zA-Z_$0-9]*$'));

update httpstubmapping set spec_json = replace(spec_json, '"anything" : "anything"', '"contains" : ""') where spec_json like '%"anything" : "anything"%';