ALTER TABLE UDP ADD "FOLDER_ID" bigint NULL;
ALTER TABLE UDP ADD FOREIGN KEY (FOLDER_ID) REFERENCES FOLDER(ID);
ALTER TABLE UDP ADD CONSTRAINT UDP_EXCLUSIVE_CONTAINER_TYPE_CONSTRAINT CHECK(TESTCASE_ID IS NULL OR FOLDER_ID IS NULL);