ALTER TABLE DATATABLE_COLUMN ALTER COLUMN TESTCASE_ID bigint NULL;
ALTER TABLE DATATABLE_COLUMN ADD "TESTSTEP_ID" bigint NULL;
ALTER TABLE DATATABLE_COLUMN ADD FOREIGN KEY (TESTSTEP_ID) REFERENCES TESTSTEP(ID) ON DELETE CASCADE;
ALTER TABLE DATATABLE_COLUMN ADD CONSTRAINT DATATABLE_COLUMN_EXCLUSIVE_CONTAINER_TYPE_CONSTRAINT CHECK((TESTCASE_ID IS NULL AND TESTSTEP_ID IS NOT NULL) OR (TESTCASE_ID IS NOT NULL AND TESTSTEP_ID IS NULL));
ALTER TABLE DATATABLE_COLUMN ADD CONSTRAINT DATATABLE_COLUMN_UNIQUE_SEQUENCE_CONSTRAINT2 UNIQUE(TESTSTEP_ID, SEQUENCE);
ALTER TABLE DATATABLE_COLUMN ADD CONSTRAINT DATATABLE_COLUMN_UNIQUE_NAME_CONSTRAINT2 UNIQUE(TESTSTEP_ID, NAME);

insert into datatable_column (name, type, sequence, teststep_id) select 'Caption', 'String', 1, id, from teststep;

delete from testcase_run;
DROP TABLE TESTSTEP_RUN;
DROP SEQUENCE TESTSTEP_RUN_SEQUENCE;