name: Build and Upload Prod Dist to Latest Release
on: [workflow_dispatch]
jobs:
  Build-and-Upload-Prod-Dist-to-Latest-Release:
    runs-on: windows-latest
    steps:
      - name: Get latest tag name
        id: get-latest-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
      - name: Check out code of latest tag
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-latest-tag.outputs.tag }}
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build Prod dist
        run: mvn clean package -P prod
      - name: List files under dist folder
        run: Get-ChildItem -Path apitestbase-assembly/dist –Recurse
      - name: Create apitestbase-dist.zip
        run: Compress-Archive -Path apitestbase-assembly/dist -DestinationPath apitestbase-dist.zip
      - name: Upload apitestbase-dist.zip to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
          files: apitestbase-dist.zip